- type: latheRecipePack
  id: ServiceDynamicFunky
  recipes:
  - PlantAnalyzer
  - BoomboxRed
  - BoomboxBlue
  - BoomboxGreen

- type: latheRecipePack
  id: ServiceMusicStaticFunky
  recipes:
  - TrumpetInstrument
  - TromboneInstrument
  - FrenchHornInstrument
  - EuphoniumInstrument
  - GunpetInstrument
  - GlockenspielInstrument
  - MusicBoxInstrument
  - XylophoneInstrument
  - MicrophoneInstrument
  - WoodblockInstrument
  - KalimbaInstrument
  - ElectricGuitarInstrument
  - BassGuitarInstrument
  - RockGuitarInstrument
  - AcousticGuitarInstrument
  - BanjoInstrument
  - ViolinInstrument
  - ViolaInstrument
  - CelloInstrument
  - SaxophoneInstrument
  - HarmonicaInstrument
  - ClarinetInstrument
  - FluteInstrument
  - RecorderInstrument
  - BagpipeInstrument